### ISSUE TITLE
When to support PDF Export 

### ISSUE THREAD

**Issue by c10ms** [KellsWorks/vue-doc-exporter#5]
It'd be great if it'll be implemented soon. Thanks.

**Comment by KellsWorks** [comment]
Resolved in the latest version 1.1.9

**Comment by KellsWorks** [comment]
This will be closed for now

**Comment by mengsuo** [comment]
Module '"vue-doc-exporter"' has no exported member 'ExportToPdf'.. i'm in 1.1.19..
