### ISSUE TITLE
ExportPDF: No pagination support

### ISSUE THREAD

**Issue by c10ms** [KellsWorks/vue-doc-exporter#7]
v1.2.1.  Here's the [Result](https://github.com/KellsWorks/vue-doc-exporter/files/13855894/ExportPDF-result.pdf), which isn't the same as [original content](https://github.com/KellsWorks/vue-doc-exporter/files/13855893/Screenshot-full.pdf)

**Comment by KellsWorks** [comment]
resolved in the latest version
